- name: Server Setup
  hosts: all
  gather_facts: no
  tags:
    - common
  tasks:
    - import_role:
        name: confluent.common

- name: Zookeeper Provisioning
  hosts: zookeeper
  gather_facts: no
  tags:
    - zookeeper
  tasks:
  - import_role:
      name: confluent.zookeeper

- name: Kafka Provisioning
  hosts: kafka_broker
  gather_facts: no
  tags:
    - kafka_broker
  tasks:
  - import_role:
      name: confluent.kafka

#- name: Kafka connect Provisioning
#  hosts: kafka_connect
#  gather_facts: no
#  tags:
#    - kafka_connect
#  tasks:
#  - import_role:
#      name: confluent.kafka_connect

# - name: ksql Provisioning
#   hosts: ksql
#   gather_facts: no
#   tags:
#     - ksql
#   tasks:
#   - import_role:
#       name: confluent.ksql
