all:
  vars:
    ansible_connection: ssh
    ansible_ssh_user: cp-kafka
zookeeper:
  hosts:
   192.168.56.102: 

kafka_broker:
  hosts:
   192.168.56.102:

# kafka_connect:
#   hosts:  
#     kafkabroker1:

# ksql:
#   hosts:  
#     kafkabroker1:

# confluent_cli:
#   hosts:
#     zookeeper1:
  
# c3:
#   hosts:
#     kafkabroker1: