confluent_user: cp-kafka
confluent_group: cp-kafka
confluent_user_home: /home/cp-kafka
confluent_home: /home/cp-kafka
confluent_appdir: "{{ confluent_home }}/confluent"
confluent_package_url: http://packages.confluent.io/archive/6.1/confluent-6.1.1.tar.gz
confluent_tar_version: confluent-6.1.1
confluent_version: confluent-6.1.1
confluent_bundle_path: "{{ confluent_home }}/bundles/{{ confluent_version }}"
tar_location: "/home/cp-kafka/"

confluent_license: ""

confluent_etc_dir: "{{ confluent_appdir }}/etc"
confluent_log_dir: "{{ confluent_appdir }}/log"
confluent_data_dir: "{{ confluent_appdir }}/dataDir"

zookeeper:
zk_port: 2181
zk_ssl_port: 2182
zk_user: cp-kafka
zk_group: cp-kafka
zk_bin_dir: "{{ confluent_appdir }}/bin"
zk_etc_dir: "{{ confluent_etc_dir }}/zk"
zk_log_dir: "{{ confluent_log_dir }}/zk"
zk_data_dir: "{{ confluent_data_dir }}/zk"

kafka_broker:
kafka_port: 9092
kafka_ssl_port: 9093
kafka_user: cp-kafka
kafka_group: cp-kafka
kafka_bin_dir: "{{ confluent_appdir }}/bin"
kafka_etc_dir: "{{ confluent_etc_dir }}/kafka"
kafka_data_dir: "{{ confluent_data_dir }}/kafka"
kafka_log_dir: "{{ confluent_log_dir }}/kafka"

kafka_connect:
kafka_connect_port: 8083
confluent_plugin_dir: "{{ confluent_appdir }}/plugins"
kafka_connect_etc_dir: "{{ confluent_etc_dir }}/kafka_connect"
kafka_connect_data_dir: "{{ confluent_data_dir }}/kafka_connect"
kafka_connect_log_dir: "{{ confluent_log_dir }}/kafka_connect"

ksql:
ksql_port: 8088
ksql_user: cp-kafka
ksql_group: cp-kafka
ksql_bin_dir: "{{ confluent_appdir }}/bin"
ksql_etc_dir: "{{ confluent_etc_dir }}/ksql"
ksql_log_dir: "{{ confluent_log_dir }}/ksql"
ksql_data_dir: "{{ confluent_data_dir }}/ksql"

confluent_cli:
confluent_cli_user: cp-kafka
confluent_cli_group: cp-kafka
confluent_cli_url: "https://s3-us-west-2.amazonaws.com/confluent.cloud/confluent-cli/archives/latest/confluent_latest_linux_amd64.tar.gz"
confluent_cli_package_name: confluent_latest_linux_amd64.tar.gz
confluent_cli_bundle: "{{ confluent_home }}/bundles"
confluent_cli_bin: "{{ confluent_home }}/bin"

confluent_control_center:
c3_user: cp-kafka
c3_group: cp-kafka
c3_port: 9021
c3_bin_dir: "{{ confluent_appdir }}/bin"
c3_etc_dir: "{{ confluent_etc_dir }}/control-center"
c3_log_dir: "{{ confluent_log_dir }}/control-center"
c3_data_dir: "{{ confluent_data_dir }}/control-center"
c3_temp_dir: "{{ confluent_appdir }}/tmp"